### ISSUE TITLE
Mimedefang 3.3 WORKER DIED UNEXPECTEDLY / line 1892

### ISSUE THREAD

**Issue by flohoff** [The-McGrail-Foundation/MIMEDefang#75] opened 2023-03-31 14:59 UTC
After i found an older issue for 2.84 i upgraded to current mimedefang 3.3 (Recompiled bookworm package for bullseye)

I still see issues like this:

```
Mar 31 16:55:41 svrh1smtpmx01p mimedefang-multiplexor[96084]: 6C716220ECB: Worker 0 stderr: open body: Invalid argument at /usr/share/perl5/MIME/Entity.pm
Mar 31 16:55:41 svrh1smtpmx01p mimedefang-multiplexor[96084]: 6C716220ECB: Worker 0 stderr: line 1892.
Mar 31 16:55:41 svrh1smtpmx01p mimedefang-multiplexor[96084]: Worker 0 died prematurely -- check your filter rules
Mar 31 16:55:41 svrh1smtpmx01p mimedefang-multiplexor[96084]: stats 1680274541.278 EndFilter worker=0 nworkers=2 nbusy=0 numRequests=153
Mar 31 16:55:41 svrh1smtpmx01p mimedefang-multiplexor[96084]: Reap: worker 0 (pid 96087) exited normally with status 22 (WORKER DIED UNEXPECTEDLY)
Mar 31 16:55:41 svrh1smtpmx01p mimedefang-multiplexor[96084]: Worker 0 resource usage: req=153, scans=153, user=13.225, sys=0.658, nswap=0, majflt=0, minflt=20610, maxrss=106016, bi=0, bo=843712
Mar 31 16:55:41 svrh1smtpmx01p mimedefang[96106]: 6C716220ECB: Error from multiplexor: ERR No response from worker
```

```
root@svrh1smtpmx01p:/var/log# dpkg -l mimedefang libmime-tools-perl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version      Architecture Description
+++-==================-============-============-=========================================
ii  libmime-tools-perl 5.509-1      all          Perl5 modules for MIME-compliant messages
ii  mimedefang         3.3-1        amd64        e-mail filter program for sendmail
```

Flo

**Comment by bigio** [comment] 2023-03-31 15:08
This should be fixed in latest code, we plan to publish a new bugfix release soon.

**Comment by flohoff** [comment] 2023-04-03 18:16
As its not the first issue in that region of code it might be a solution to put this into an eval block and make the die/unexpected behaviour configurable. Before "loosing" mail i'd rather pass it on.

Flo

**Comment by bigio** [comment] 2023-04-04 06:25
It seems a duplicate of #74 is your mimedefang-filter(5) similar ?

**Comment by flohoff** [comment] 2023-04-07 17:44
I am not seeing the first like as in #74 "open body: Invalid argument at /usr/pkg/lib/perl5/vendor_perl/5"

I havent modified the filters except adding typical microsoft office format extensions e.g. doc, docx, ppt, pptx, etc.

I am now running on the latest git i built a package from:

mimedefang_3.3+git7bf609-1_amd64.deb

For now it seems okay.

Flo

**Closed as completed** 2023-04-11 23:15 UTC
