### ISSUE TITLE
Problem md_check_against_smtp_server() after update to version 2.85 (CentOS 7)

### ISSUE THREAD

**Issue by ez-w** [The-McGrail-Foundation/MIMEDefang#50] opened 2021-12-03 22:42 UTC
Hi,

I use MIMEDefang on two server and the function md_check_against_smtp_server() (version mimedefang-2.84-1.el7, perl-IO-Socket-SSL-1.94-7.el7)

If I update one server to version mimedefang-2.85-1.el7 the function return always tempfailed result and the email stay in SMTP queue

**mimedefang.pl[1877]: 1B3LSO9x010710: filter_recipient tempfailed recipient <email@email.com>
Dec  3 21:55:57 mx sendmail[5114]: 1B3KtvRh005114: Milter: to=<xxxxx@xxxx.xxx>, reject=451 4.3.0 Could not connect to other SMTP server smtpserver.xxxx.xxxx**

The SMTP destination server has Sendmail 8.14.7 and I see this errors in sendmail with debug level 15

_Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 220 smtpserver.xxxx.xxxx ESMTP Fri, 3 Dec 2021 21:55:57 +0100
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: <-- \026\003\001\002
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: Sending "\026\003\001\002" to Milter
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 500 5.5.1 Command unrecognized: "\026\003\001\002"
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: <--
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: Sending "" to Milter
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 500 5.5.1 Command unrecognized: ""
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: <--
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: Sending "" to Milter
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 500 5.5.1 Command unrecognized: ""
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: <--
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: Sending "" to Milter
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 500 5.5.1 Command unrecognized: ""
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: <--
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: Sending "" to Milter
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 500 5.5.1 Command unrecognized: ""
Dec  3 21:55:57 mail sendmail[27552]: 1B3Ktvk8027552: --- 421 4.4.1 smtpserver.xxxx.xxxx Lost input channel from [xxx.xxx.xxx.xxx]_

If I copy the file /usr/bin/mimedefang.pl from 2.84 version to the server with version 2.85 the problem disappears and the email is directly send.

It's a TLS problem/incompatibility with the new version of mimedefang.pl file ?
 
Thanks

**Comment by bigio** [comment] 2021-12-05 15:41
The MIMEDefang log line is missing the connection error, it should be similar to:
Dec 3 21:55:57 mx sendmail[5114]: 1B3KtvRh005114: Milter: to=xxxxx@xxxx.xxx, reject=451 4.3.0 Could not connect to other SMTP server smtpserver.xxxx.xxxx: **Connection timed out**

MIMEDefang 2.84 works because it doesn't try TLS connections.

Are you able to connect to the smtp server using openssl(1) command ?
You can use this command:
openssl s_client -starttls smtp -crlf -connect smtpserver.xxxx.xxxx:25

**Comment by ez-w** [comment] 2021-12-05 19:47
yes it's working

> openssl s_client -starttls smtp -crlf -connect smtpserver.xxxx.xxxx:25
...
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 4806583798C15FAA2C2C....
    Session-ID-ctx: 
    Master-Key: 502F9634E9F950CA10....
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 1 (seconds)
    TLS session ticket:
...

    Start Time: 1638733448
    Timeout   : 300 (sec)
    **Verify return code: 0 (ok)**
---
250 HELP
quit
221 2.0.0 smtpserver.xxxx.xxxx closing connection
closed

**Comment by bigio** [comment] 2021-12-06 08:31
Could you send me your server hostname in private at giovanni at paclan dot it in order to reproduce the issue  and find a fix ?

**Comment by bigio** [comment] 2021-12-09 11:10
fixed by commit d7f5d9c2865457897896d89915d258311abf23e8

**Closed as completed by bigio** 2021-12-09 11:10 UTC
